### PR TITLE
Adds support for additional keys

### PR DESCRIPTION
**Pull request by ProjektGopher**
This narrowly targeted PR adds support for the `ESC` key, as well as `shift + up` and `shift + down`.

This may allow new prompts to be backed out of, or scrolled through more quickly.

### CODE REVIEW

**Comment by ProjektGopher** [comment]
Marked as draft, but this is ready to go once reviewed.

**Comment by driesvints** [comment]
@ProjektGopher draft PR's aren't reviewed. Please mark this as ready if you need one.

**Comment by ProjektGopher** [comment]
Thx @driesvints, I thought marking as draft was part of Larave's process for this repo since my other PR got marked as draft without comment. Thx for the heads-up.

**Comment by taylorotwell** [comment]
Adds support for the `ESC` key to do what action?

**Comment by ProjektGopher** [comment]
@taylorotwell I've got a prompt that I've built that allows you to hit escape in order to back out and return `null` if `required` is set to `false`.

**Pull request merged**
