### PR TITLE
Add info note

### PR DESCRIPTION
**Pull request by sebastianpopp**
I'm using prompts outside of Laravel and think it would be helpful to be able to display a simple success message the same way I can display an error message. The name of the function is based on the function in Laravel commands.

### CODE REVIEW

**Comment by jessarcher** [comment]
Thanks for the PR, @sebastianpopp!

It's cool to hear you're using Prompts in other PHP projects and that you found the note components!

I'm okay with merging this, but I'm not 100% sure what the future holds for the notes (and spinner), which are currently undocumented. I think they're very useful, but they don't completely replace the informational components from Symfony, like tables and progress bars. I haven't had time to think about where the "non-prompting" parts of Prompts fit and the value they can bring. In any case, I don't anticipate us removing them, but they could potentially take a different shape in a later release.

**Review by jessarcher — APPROVED** [review]

**Comment by utsavsomaiya** [comment]
In the Laravel application, we have a mix and match situation concerning helper function names. Currently, the helper function info is used to interact with the Log channel. To enhance clarity and avoid conflicts, I suggest renaming this helper function to success. By doing so, we can easily differentiate between logging information and indicating a successful operation.

what do you think @jessarcher?

**Comment by jessarcher** [comment]
> In the Laravel application, we have a mix and match situation concerning helper function names. Currently, the helper function `info` is used to interact with the Log channel. To enhance clarity and avoid conflicts, I suggest renaming this helper function to `success`. By doing so, we can easily differentiate between logging information and indicating a successful operation.
> 
> what do you think @jessarcher?

I don't have a strong opinion. The prompt functions are all namespaced, so there is no conflict. The `info` name matches the corresponding `$this->info()` method in Artisan console commands, but I understand it's not ideal to share a name as Laravel's global `info` function and need to alias an import if you want to use both in the same file.

I'll need to think more about the role of these functions and have a chat with Taylor. I probably should have left them out of the package until I had a clearer picture for them.

**Comment by utsavsomaiya** [comment]
No worries dear. Thanks.

**Pull request merged**
