### PR TITLE
Support Laravel 9

### PR DESCRIPTION
**Pull request by danharrin**
Many packages in the Laravel ecosystem still support Laravel 9 (Livewire, Inertia, Filament, many Spatie packages with commands), and it would be great if they could make use of prompts to enhance their UX.

I have ensured that GitHub actions runs tests using Laravel 9, and they appear to be passing. Please let me know if I've made an oversight here and there is a reason why it's not currently supported.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Hmm, I think my main hesitation is this binds us to Laravel 9 until the next major release of Prompts - not letting us take advantage of anything that is introduced to Laravel 10 in the meantime.

**Comment by danharrin** [comment]
That's fair enough, but the only new features you would actually be able to take advantage of are from `illuminate/collection`, and everything that has already been achieved with prompts so far doesn't require L10.to

My issue is that to be able to use prompts, we have to drop Laravel 9 support from packages, while its still a security-supported release by you guys, and I don't think users would be too happy with that. So in the end, we just won't end up using prompts, which would be a shame.

At the end of the day having this is not a huge deal, but it would be really nice if we could make good use of all the fantastic work that has been done with this package, and push it out to loads more users.

**Comment by awcodes** [comment]
Couldn’t this have possible impacts on Livewire too if it still supports Laravel 9?

**Comment by jhonoryza** [comment]
@danharrin can you add support for php 8.0 i am still using laravel 9 with php 8.0 :)

**Comment by HassanZahirnia** [comment]
Please approve this PR, wanna use this in our projects as well 🙌 Thank you 😊

**Comment by taylorotwell** [comment]
With Laravel 11 coming this winter I don't want to bind us to Laravel 9. If the upgrade path from 9 to 10 was significant I would agree with this but the upgrade path is relatively trivial and takes just a few minutes.

**Pull request closed without merging**
