### PR TITLE
Replace tput command as it's not available on all OSes

### PR DESCRIPTION
**Pull request by digiservnet**
The `tput` command isn't available by default in the Alpine Linux official PHP docker images (at least) and this throws an `InvalidArgumentException` for truncation length.

This PR replaces the `tput` command with method calls from the Symfony Console `Terminal` class.

`tput` is used in the `Terminal` class to determine the number of rows and columns available, in particular used for truncating line length if available terminal columns are too low.

### CODE REVIEW

**Comment by jessarcher** [comment]
Thanks!

I wonder if we could change the approach or add a fallback...

For example, `stty size` returns the lines and columns separated by a space on Linux, and we're already using `stty` elsewhere. Does that work in Alpine?

I'd just need a macOS friend to check whether that works and returns the same format for them, and then we could just drop `tput` altogether.

**Comment by digiservnet** [comment]
Tested and `stty size` works fine in Alpine. If this can be confirmed on a mac (from looking around on the interwebz, it does produce the same `rows cols` format), I can push the changes. 🙂

**Comment by digiservnet** [comment]
Had confirmation that `stty` behaves the same on macOS so have gone with this approach.

Also added Windows detection and utilised `mode` there. The output from this is:
```bash
mode CON
```

```bash

Status for device CON:
----------------------
    Lines:          42
    Columns:        180
    Keyboard rate:  31
    Keyboard delay: 0
    Code page:      850
```

**Comment by digiservnet** [comment]
Good call @wouterj. I've replaced the custom code with the Symfony Terminal `getWidth()` and `getHeight()` method calls as there doesn't seem much reason to duplicate this functionality 🙂

**Comment by jessarcher** [comment]
Thanks!

**Pull request merged**
